@Api_HostAddress = http://localhost:5050/mini-api
@Api_Token = 1234567890

### Get cities
GET {{Api_HostAddress}}/api/cities?$token={{Api_Token}}
Accept: application/json

### Get city by ID
GET {{Api_HostAddress}}/api/cities/1581993880251010022?$token={{Api_Token}}
Accept: application/json
